- .github/pull_request_template.md
NOTE: Once this is in dev it will pre prop the pr template
I have copy and pasted the template to show how it will look...  when reviewing the `md` file please note that text within `` is commented out and only seen when the PR is in edit mode.  This will not be seen once work is saved and is only to provide context and help when filling out the template.
[DIGITAL-109](https://cm-jira.usa.gov/browse/DIGITAL-109)
This PR will set up a PR Template for the team to follow in order to standardize our PR review process. 
None
Review the new template suggestion and ensure steps and suggestion make sense and are appropriate for our project and workflow.
> DIGITAL-109: Proposed PR template

- config/sync/workflows.workflow.editorial.yml
[DIGITAL-34](https://cm-jira.usa.gov/browse/DIGITAL-34)
Added all workflow states and transitions.
None
Config can be found at /admin/config/workflow/workflows/manage/editorial
At minimum, import configuration
States and transitions listed should match those of the Jira ticket.
- [ x] A link to the JIRA ticket has been included above.
- [x ] No merge conflicts exist with the target branch.
- [x ] A reviewer has been designated.
- [x ] Deployment and testing steps have been documented above, if applicable.
- [ x] The file changes are relevant to the task objective.
- [x ] Code is readable and includes appropriate commenting.
- [ x] Code standards and best practices are followed.
- [x ] Applicable logs are free of errors.
> DIGITAL-34: Update workflow states and transitions.

- .github/workflows/database-backup.yml
- README.md
- scripts/cloud-gov-s3-creds.sh
- scripts/pipeline/database-backup.sh
- scripts/pipeline/deb-cf-install.sh
- scripts/pipeline/github-exports.sh
- web/sites/default/settings.php
[DIGITAL-178](https://cm-jira.usa.gov/browse/DIGITAL-178)
Adds database backup functionality to the pipeline.
> DIGITAL-178: Database Backup

- .gitignore
- config/sync/views.view.moderated_content.yml
- terraform/applications/nginx-waf/nginx/conf.d/default.conf
[DIGITAL-174](https://cm-jira.usa.gov/browse/DIGITAL-174)
The dropdown on 'Moderation state' drop down here http://digitalgov.lndo.site/admin/content/moderated was missing all the available statuses from http://digitalgov.lndo.site/admin/config/workflow/workflows/manage/editorial.
Visit http://digitalgov.lndo.site/admin/content/moderated and ensure 'Moderation state' from http://digitalgov.lndo.site/admin/config/workflow/workflows/manage/editorial are present.
> DIGITAL-174: Moderated content view missing all states

- CONTRIBUTING.md
- README.md
[DIGITAL-176](https://cm-jira.usa.gov/browse/DIGITAL-176)
Remove external documentation links and put documentation in CONTRIBUTING.md.
None
> DIGITAL-176: Move drupal env lando info into Contributing.md.

- composer.json
- composer.lock
- composer.log
- config/sync/core.extension.yml
- config/sync/google_tag.container.GTM-MZCKZPQ.675b35536672a7.15039879.yml
- config/sync/google_tag.settings.yml
- web/modules/custom/ec_shortcodes/templates/ec-shortcodes-featured-resource-ext.html.twig
- web/modules/custom/ec_shortcodes/templates/ec-shortcodes-featured-resource.html.twig
- web/sites/default/settings.cloudgov.php
- web/sites/default/settings.php
- web/themes/custom/digital_gov/templates/node/node--basic-page.html.twig
- web/themes/custom/digital_gov/templates/node/node--community.html.twig
- web/themes/custom/digital_gov/templates/node/node--event.html.twig
- web/themes/custom/digital_gov/templates/node/node--news.html.twig
- web/themes/custom/digital_gov/templates/node/node--resources.html.twig
- web/themes/custom/digital_gov/templates/node/node--topics.html.twig
- web/themes/custom/digital_gov/templates/paragraph/paragraph--external-content--default.html.twig
- web/themes/custom/digital_gov/templates/paragraph/paragraph--external-content--featured-links.html.twig
- web/themes/custom/digital_gov/templates/paragraph/paragraph--internal-content--default.html.twig
- web/themes/custom/digital_gov/templates/paragraph/paragraph--internal-content--featured-links.html.twig
[DIGITAL-40](https://cm-jira.usa.gov/browse/DIGITAL-40)
This PR will set up GTM module with property id for the current site and only have it set to track on the prod evn
N/A
1. Load the site locally and compare the GTM script to what is found on the live site
> DIGITAL-40: Install GTM and set up ID

- config/sync/core.entity_form_display.node.event.default.yml
- config/sync/field.field.node.event.field_venue.yml
[DIGITAL-197](https://cm-jira.usa.gov/browse/DIGITAL-197)
This PR will update the description of the venue field and setting it to be collapsed until the user would like to open and update it
`lando rebuild -y`
visit `http://digitalgov.lndo.site/node/add/event` and check that the description has been updated and that is is collapsed and will open when the user selects it.
> DIGITAL-197: Update Venue Field

- composer.json
- composer.lock
- composer.log
- composer.sh
- config/sync/core.entity_form_display.node.source.default.yml
- config/sync/core.extension.yml
- config/sync/rabbit_hole.behavior_settings.default.yml
- config/sync/rabbit_hole.behavior_settings.default_bundle.yml
- config/sync/rabbit_hole.behavior_settings.node_type_guide_navigation.yml
- config/sync/rabbit_hole.behavior_settings.node_type_short_post.yml
- config/sync/rabbit_hole.behavior_settings.node_type_source.yml
- config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_hcd_glossary.yml
- config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_resource_topics.yml
- config/sync/rabbit_hole.behavior_settings.user.yml
[DIGITAL-141](https://cm-jira.usa.gov/browse/DIGITAL-141)
Installs and enables the rabbit hole module.
Enables the rg_node submodule
Configures the short post, source, and guide nav content types to 404 when viewed
[DIGITAL-47](https://github.com/GSA/digital-gov-drupal/pull/82) which adds the guide nav content type.
`lando si` 
Visit the short post, source, and guide nav nodes and confirm they show a 404 message
> DIGITAL-141: Install Rabbit Hole module

- composer.json
- composer.lock
- composer.log
- config/sync/config_ignore.settings.yml
- config/sync/core.extension.yml
- config/sync/system.site.yml
[DIGITAL-46](https://cm-jira.usa.gov/browse/DIGITAL-46)
Adding Config ignore for metatags and googletags
n/a
`lando rebuild -y`
visit `/admin/config/development/configuration/ignore/` and verify that the metatag and google_tag is listed on the ignore
> DIGITAL-46: Enable and add Config Ignore

- composer.patches.json
[DIGITAL-204](https://cm-jira.usa.gov/browse/DIGITAL-204)
* Adds drupal core patch to allow colons and other valid CSS identifiers in classes specified via Views UI
`composer install` should patch core
Find or create a view where classes have been customized with identifiers that include a `:`. View rendered output for the view and confirm the classes in the HTML have the `:` in them.
> DIGITAL-204: Patched allowed CSS chars

- .github/workflows/database-backup.yml
- .github/workflows/generate-static-run-dev.yml
- .github/workflows/generate-static-run-prod.yml
- .github/workflows/generate-static-run-stage.yml
- .github/workflows/generate-static.yml
- scripts/bash_exports.sh
- scripts/post-deploy
- scripts/upkeep
[DIGITAL-241](Static site generation)
Generates the static site.
> DIGITAL-241: Static site generation.

- .lando.dist.yml
- composer.json
- composer.lock
- composer.log
- lando-config/my.cnf
- web/sites/default/default.services.yml
- web/sites/default/default.settings.php
- web/sites/default/settings.cloudgov.php
- web/sites/default/settings.php
- web/sites/development.services.yml
- web/sites/example.sites.php
- web/themes/custom/digital_gov/digital_gov.theme
- web/themes/custom/digital_gov/templates/node/node--event--teaser.html.twig
- web/themes/custom/digital_gov/templates/node/node--guides.html.twig
- web/themes/custom/digital_gov/templates/node/node--news--teaser.html.twig
- web/themes/custom/digital_gov/templates/partials/guides/guide-content.html.twig
[DIGITAL-307](https://cm-jira.usa.gov/browse/DIGITAL-307)
Update all dependencies to provide security updates and patches.
Ensure that the site loads as it did before.
> DIGITAL-307 update deps

- composer.json
- composer.lock
- composer.log
- config/sync/config_ignore.settings.yml
- config/sync/core.extension.yml
- config/sync/role_watchdog.settings.yml
- config/sync/upgrade_status.settings.yml
- config/sync/views.view.role_watchdog_history.yml
- config/sync/views.view.track_role_grants.yml
- config/sync/views.view.track_role_history.yml
https://cm-jira.usa.gov/browse/DIGITAL-283
`lando si` to install module and enable.
1. Role Watchdog: 
- log into the site and visit http://digitalgov.lndo.site/user/2/edit and change the role of user and save
- visit and see the role change record on http://digitalgov.lndo.site/admin/role-watchdog-history
2. Upgrade status:
- visit http://digitalgov.lndo.site/admin/reports/upgrade-status and see the upgrade status report of the site
3. Database ssl check:
- visit http://digitalgov.lndo.site/admin/reports/status#checked and note record of database check
> DIGITAL-283 install and configure security modules

- web/themes/custom/digital_gov/templates/node/node--basic-page.html.twig
https://cm-jira.usa.gov/browse/DIGITAL-250
`lando drush cr`
1. visit http://digitalgov.lndo.site/about and confirm only the body field value is displayed.
> DIGITAL-250 Update template to match digital.gov

- .bp-config/php/fpm.d/stdout.conf
[DIGITAL-158](https://cm-jira.usa.gov/browse/DIGITAL-158)
Ran into https://github.com/cloudfoundry/php-buildpack/issues/256#issuecomment-372144456 when trying to figure out why logging was not working. Apparently Nginx sends stdout to /dev/null by default. This configuration disables that.
> DIGITAL-158: Configure Nginx to not send stdout messages to /dev/null.

- composer.json
- composer.lock
- composer.log
- config/sync/core.extension.yml
- config/sync/filter.format.html.yml
- config/sync/filter.format.multiline_inline_html.yml
[DIGITAL-299](https://cm-jira.usa.gov/browse/DIGITAL-299)
* Adds the Auto Heading IDs module
* Configure the html and multiline_inline_html text formats to add autogenerated ID attributes for headings.
In HCD guides, the sidnav to the left of the content on [some pages|https://digital.gov/guides/hcd/discovery-operations/] has internal links to headings on the page. The hugo site automatically generated IDs for headings in the body content. This module does the same for Drupal via the two text format configs.
run `composer install` then `lando si` on this branch.
1. Go to https://digitalgov.lndo.site/guides/site-scanning#content-start
2. Hover over "Access the data directly" in sidenav, confirm the URL contains a link to an internal anchor `#accesss-the-data-directly`
3. Clicking on …
> DIGITAL-299: Add and configure auto heading IDs

- config/sync/system.site.yml
- config/sync/views.view.news_and_events.yml
- web/themes/custom/digital_gov/templates/node/node--event--teaser.html.twig
- web/themes/custom/digital_gov/templates/node/node--landing-page--homepage.html.twig
- web/themes/custom/digital_gov/templates/node/node--short-post--teaser.html.twig
- web/themes/custom/digital_gov/templates/partials/home/news-featured.html.twig
https://cm-jira.usa.gov/browse/DIGITAL-248
Configure the homepage news and events widget.
For proper styling to apply #148 must be merged first.
`lando si`
1. visit http://digitalgov.lndo.site/ news and events component should be displaying on the page matching digital.gov. There should be news and event in desc chron order with any future events at slot 3 and 9.
2. Test publishing a new news article and make sure it gets sorted correctly based on authored on date.
3. Test publishing a new past event and make sure it gets sorted correctly based on end date.
4. Test publishing a new future event and make sure it gets into slot 3 or 9 depending on the date. Future events are orders in asc chron order 3 then 9. Only 2 future events should show.
> DIGITAL-248: Configure homepage news and events widget

- config/sync/views.view.featured_communities.yml
- web/modules/custom/default_content_config/content/node/1af1ac07-e1c2-4cc9-a974-526f4d27259d.yml
[DIGITAL-246](https://cm-jira.usa.gov/browse/DIGITAL-246)
I missed this bug when reviewing the PR for this.
Communities to highlight should be greater than or equal to one.
Updates short name for the all fields community node to prevent confusing it with another node with same title.
`lando si` 
Homepage and communities page should display 4 nodes, 3 of which have a page weight of 1.
> DIGITAL-246: Fix page weight operator for featured communities view 

- web/modules/custom/dg_fields/dg_fields.module
[DIGITAL-]()
Allows only a limited set of vocabularies as valid options for the glossary field for a guide node.
Currently, the only vocab that should show as a glossary option for guides ins "HCD Glossary". This PR filters the allowed values for that field to ones with a machine name ending in `_glossary` so we can add other guide glossaries in the future.
Vocabularies aren't fieldable, so one direct way to control which ones show up as options is by checking the machine name.
`lando si` would work but `drush cr` to pick up the preprocess hook should be sufficient.
Edit a content page, confirm the only option under "Glosarry" select is "HCD Glossary"
> DIGITAL-291: Limit glossary ref options

- composer.json
- composer.lock
- composer.log
- config/sync/core.extension.yml
- config/sync/editor.editor.html.yml
- web/modules/custom/convert_text/src/ConvertText.php
[DIGITAL-96](https://cm-jira.usa.gov/browse/DIGITAL-96)
Display emojis in HTML filter. Adds button to CKEditor for inserting emojis. 
Updates the convert text class to lookup colon-sequences like `:smile:` or `:gear:` and replace them with the unicode equivalent for that emoji.
`lando si`
Go to https://digitalgov.lndo.site/admin/convert-text and enter a string with colon sequences like `:envelope: :tada:, :video_camera:, :gear:` should see it converted:
> DIGITAL-96: Implement Support Emojis

- config/sync/editor.editor.html.yml
- config/sync/filter.format.html.yml
- web/themes/custom/digital_gov/templates/media/media--image.html.twig
https://cm-jira.usa.gov/browse/DIGITAL-351
Enable media display override for HTML text format.
`lando si`
1. Visit http://digitalgov.lndo.site/node/add/basic_page
2. Add an Image to the wysiwyg using the Media button
3. Switch the image display from default to Media library
4. Add an alignment option
> DIGITAL-351: Add media display override for HTML text format

- web/themes/custom/digital_gov/package-lock.json
- web/themes/custom/digital_gov/package.json
[DIGITAL-392](https://cm-jira.usa.gov/browse/DIGITAL-392)
Removes `npm-run-all` that has a dependency `cross-spawn` that is out of date.
This syncs Drupal npm packages with Digital.gov, see https://github.com/GSA/digitalgov.gov/pull/8031.
Removed typescript commands since we are no longer using typescript for image uploading and these files have been removed all ready.
`npm install` to update packages.
`npm start` should run successfully.
> POAM — DIGITAL-392: Replace npm-run-all with concurrently

- web/themes/custom/digital_gov/package-lock.json
[DIGITAL-392](https://cm-jira.usa.gov/browse/DIGITAL-392)
Bumps `nanoid` from `3.3.7` to `3.3.8`.
Run `npm install` and `npm start`.
`npm audit` should display no warnings.
> POAM — DIGITAL-392: Bump nanoid to 3.3.8

- web/sites/default/settings.php
- web/sites/example.settings.local.php
- web/themes/custom/digital_gov/templates/block/block--site-wrapper-notice-bar.html.twig
[DIGITAL-376](https://cm-jira.usa.gov/browse/DIGITAL-376)
Shows the preview banner on non-production that currently shows on the 'federalist' non-prod sites for Hugo.
As long as env is running, no special setup.
If you would like to see the banner on in your local, add `$config['environment']['env_non_prod_remote'] = TRUE;` to your `settings.local.php`. This is the same way that it is enabled for prod only.
> DIGITAL-376: Enable preview banner on production.

- web/themes/custom/digital_gov/digital_gov.theme
[DIGITAL-338](https://cm-jira.usa.gov/browse/DIGITAL-338)
There is a message displaying in news for archived articles > 5 years. Don't show this.
Definition Of Done is that this message is set to false. 
This is not easy to test, since you would need a >5 year old article. Developers can go to the digital_gov.theme and see where the code has been changed from this:
```
Line 121:  switch ($variables['node']->bundle()) {
case 'news':
$before_date = new DrupalDateTime('5 years ago');
$variables['show_archive_warning'] = $created->getPhpDateTime() <= $before_date->getPhpDateTime();
break;
```
to:
```
Line 121: switch ($variables['node']->bundle()) {
case 'news':
// Disable this archive warning, see DIGITAL-336.
$variables['show_archive_warning'] = FALSE;
break;
```
> DIGITAL-338: Disable archive message on news.

- composer.lock
- composer.log
[DIGITAL-402](https://cm-jira.usa.gov/browse/DIGITAL-402)
Update our dependencies for security and patches.
Ensure the site works as before.
> DIGITAL-402: Update dependencies.

- MIGRATE.md
- composer.json
- composer.lock
- composer.log
- composer.patches.json
- config/sync/core.extension.yml
- config/sync/migrate_plus.migration_group.default.yml
- migrate.sh
- web/modules/custom/digital_gov_migration/digital_gov_migration.info.yml
- web/modules/custom/digital_gov_migration/digital_gov_migration.module
- web/modules/custom/digital_gov_migration/migrations/json_authors.yml
- web/modules/custom/digital_gov_migration/migrations/json_events.yml
- web/modules/custom/digital_gov_migration/migrations/json_images.yml
- web/modules/custom/digital_gov_migration/migrations/json_images_to_media.yml
[DIGITAL-378](https://cm-jira.usa.gov/browse/DIGITAL-378)
Provide the images, media images, author, and events migrations.
See MIGRATION.md.
One should be able to `./drush.sh migrate:import --all` to import all the migrations.
> DIGITAL-378: First migrations

- web/modules/custom/default_content_config/content/user/280a2f72-f105-4dcb-b81f-fae216ed62de.yml
https://cm-jira.usa.gov/browse/DIGITAL-444
Update user to GSA email
`lando si`
1. visit http://digitalgov.lndo.site/user/19/edit and confirm the email is set to gsa.gov email.
> DIGITAL-444: Update user to gsa email

- config/sync/user.role.user_admin.yml
https://cm-jira.usa.gov/browse/DIGITAL-416
Add permission for User Admin role to assign Author role.
`lando si`
1. Log in as super admin
2. Create a new test user account with role of "Authenticated user"
3. Create a new test user account with role of "User Admin"
4. Masquerade as the test user with the role "User Admin"
5. Update the "Authenticated user" test account and assign the "Author" role.
6. Confirm that you can see the checkbox for adding the Author role and that you can save.
> DIGITAL-416: Add permission for User Admin role to assign Author role

- config/sync/config_ignore.settings.yml
- config/sync/user.role.data_analyst.yml
[DIGITAL-415](https://cm-jira.usa.gov/browse/DIGITAL-415)
Update the Data Analyst to have permission on GTM, Meta tags, and pathauto patterns.
`lando cim`
Data Analyst User should be able to: 
- see configuration in Toolbar
- update google tag settings - /admin/config/services/google-tag
- Configure URL Alias - /admin/config/search/path
- Configure Pathauto patterns - /admin/config/search/path/patterns
- Configure metatag settings - /admin/config/search/metatag
When exporting config, none of the following should not export because they are all being ignored by "config_ignore"
- GTM
- Meta tags
- Pathauto patterns
> DIGITAL-415: Update permission for Data Analysts

- config/sync/user.role.identifier_admin.yml
https://cm-jira.usa.gov/browse/DIGITAL-448
Add permission to allow Identifier Admin role to access the content overview page via the admin toolbar.
`lando si`
1. Log into your local site
2. Masquerade as a user with the Identifier Admin role.
3. Confirm that you can see the "Content" menu item with a dropdown that contains the "Identifier" in the admin toolbar. 
4. Click on the Identifier link and confirm that you can visit the page.
> DIGITAL-448: allow Identifer Admin access to content overview page

- .cfignore
- .github/workflows/cloudgov-deploy-app.yml
- apt.yml
- composer.json
- composer.lock
- composer.log
- config/non_local/new_relic_rpm.settings.yml
- config/sync/config_split.config_split.non_local.yml
- manifest.yml
- scripts/bootstrap.sh
- scripts/cloud-gov-s3-creds.sh
- web/sites/default/settings.cloudgov.php
https://cm-jira.usa.gov/browse/DIGITAL-426
https://cm-jira.usa.gov/browse/DIGITAL-359
Install and enable New Relic RPM module for non_local split
Confiigure New Relic agent in system
`lando si`
1. Set your local environment to non_local split and run `lando drush cim`
2. Visit http://digitalgov.lndo.site/admin/config/development/new-relic and confirm New Relic RPM module is installed and ready for configuration.
> DIGITAL-359: Implement New Relic.

- composer.lock
- composer.log
[DIGITAL-457](https://cm-jira.usa.gov/browse/DIGITAL-457)
Update our dependencies for security and patches.
Ensure the site works as before.
> DIGITAL-457: Update Dependencies

- composer.json
- composer.lock
- composer.log
- config/sync/core.entity_form_display.node.event.default.yml
- config/sync/core.entity_form_display.node.guides.default.yml
- config/sync/core.entity_form_display.node.news.default.yml
- config/sync/core.entity_form_display.node.resources.default.yml
- config/sync/core.entity_form_display.node.short_post.default.yml
- config/sync/core.entity_form_display.node.topics.default.yml
- config/sync/core.entity_form_display.paragraph.internal_content.default.yml
- config/sync/core.extension.yml
[DIGITAL-447](https://cm-jira.usa.gov/browse/DIGITAL-447)
- Update all reference fields that were using "Inline Entity Form" are now "Autocomplete Deluxe" widgets or "Autocomplete" widgets
- Remove the "Inline Entity Form" Module
Here is a list of fields that have changed and can be reviewed via the edit form or the add new form for the content type:
| Entity Types | Field                                                                   | Field Name                                          |
| ------------ | ----------------------------------------------------------------------- | --------------------------------------------------- |
| Event        | field_authors                                                           | Authors …
> DIGITAL-447: Replace Inline Entity Form Fields

- web/themes/custom/digital_gov/templates/node/node--community.html.twig
[DIGITAL-466](https://cm-jira.usa.gov/browse/DIGITAL-466)
Communities Page still displays placeholder text - [placeholder Upcoming events]
This ticket is NOT to build the functionality, that will come in future ticket [DIGITAL-293](https://cm-jira.usa.gov/browse/DIGITAL-293). This ticket is just to remove the placeholder from this display for go live.
`lando cr`
1. Navigate to any community page
- Example:https://digitalgov.lndo.site/communities/plain-language
2. You should not see [placeholder Upcoming events]
> DIGITAL-466: Remove placeholder text from display

- config/sync/core.entity_form_display.node.basic_page.default.yml
- config/sync/core.entity_form_display.node.community.default.yml
- config/sync/core.entity_form_display.node.event.default.yml
- config/sync/core.entity_form_display.node.guide_landing.default.yml
- config/sync/core.entity_form_display.node.guides.default.yml
- config/sync/core.entity_form_display.node.landing_page.default.yml
- config/sync/core.entity_form_display.node.news.default.yml
- config/sync/core.entity_form_display.node.resources.default.yml
- config/sync/core.entity_form_display.node.short_post.default.yml
- config/sync/core.entity_form_display.node.topics.default.yml
- config/sync/core.entity_form_display.paragraph.external_content.default.yml
- config/sync/core.entity_form_display.paragraph.internal_content.default.yml
[DIGITAL-525](https://cm-jira.usa.gov/browse/DIGITAL-525)
Some fields have a character limit, current content does not have this limit. This could cause issues with migrated content getting truncated when node is resaved.
The site can use a soft limit instead of a hard one using the current module. 
`lando si`
1. Navigate to any of the listed node creation or edit pages.
2. Enter content in field listed (you will see text about limits)
3. You should see that you can type in more content than the max and the char count will go into the negative
4. Save the node
5. You should see that Content displayed is not cut off
6. Edit node again and see that content is all still there on the edit screen
**Effected Fields**
Basic Page, 
Community, 
Event, 
Guides, 
Page, 
News, 
Resources, 
Short …
> DIGITAL-525: Change char limit to a soft limit

- composer.lock
- composer.log
[DIGITAL-530](https://cm-jira.usa.gov/browse/DIGITAL-530)
Update composer dependencies.
Ensure that the site general performs as before.
> DIGITAL-530: Updated dependencies.

- config/sync/metatag.metatag_defaults.front.yml
- config/sync/metatag.metatag_defaults.global.yml
[DIGITAL-527](https://cm-jira.usa.gov/browse/DIGITAL-527)
Updated <title> tag to match production
1. Navigate to the homepage. Compare the title on the tab to the title on the tab on the live site. They should be the same.
Note: This separator on the homepage is a **emdash**
2. Navigate to any other page on the site. Compare the same way.
Note: This separator when anywhere but the homepage is a **endash**.
These values can also be tested by comparing the source <title> tag.
> DIGITAL-527: Update <title> tag

- .cfignore
- orch/deploy_install.sh
[DIGITAL-473](https://cm-jira.usa.gov/browse/DIGITAL-473)
Robotstxt module was configured with the defaults instead of our exported configuration.
Removed the cfignore items that were trying to target Robo PHP files that were not really hurting anything that incidentally targeted robotstxt config.
> DIGITAL-473: Cfignore caused robotstxt module to not be configured properly

- web/themes/custom/digital_gov/css/new/_uswds-theme.scss
- web/themes/custom/digital_gov/templates/system/status-messages.html.twig
[DIGITAL-506](https://cm-jira.usa.gov/browse/DIGITAL-506)
Add styles to Drupal messages
**Example 1**: Clear caches in the UI and the Clear caches message will appear for you to see styles applied
**Example 2**: Manually add messages in the theme temporarily
1. Edit `/web/themes/custom/digital_gov/digital_gov.theme` and add the following:
- At the top of the file add add use statement `use Drupal\Core\Messenger\MessengerInterface;`
- in the `digital_gov_preprocess_node` add the following
```php
$messenger = \Drupal::messenger();
$messenger->addMessage(t('This is an Default informational message.'));
$messenger->addMessage(t('This is an informational message.'), MessengerInterface::TYPE_STATUS);
$messenger->addMessage(t('This is a warning message!'), …
```
> DIGITAL-506: Drupal Message Styles

- web/themes/custom/digital_gov/templates/partials/guides/guide-menu-bar.html.twig
[DIGITAL-335](https://cm-jira.usa.gov/browse/DIGITAL-335)
For the guides:
- remove a backtick in the guides mobile menu
- adds the link and title to the icon in guides mobile menu, wasn't using drupal paths
<details>
<summary>Extra Backtick</summary>
</details>
<details>
<summary>Fix Link & Title for Mobile Menu</summary>
</details>
> DIGITAL-335: Guides — Removes backtick, update twig mobile menu link & title

- config/sync/field.field.node.short_post.field_source.yml
- config/sync/field.storage.node.field_short_post_type.yml
- web/modules/custom/default_content_config/content/node/30e4505c-8011-493a-a3e8-ad35ef95c29d.yml
- web/modules/custom/default_content_config/content/node/d22455bc-ccf3-4079-a2bb-ecf67310af4b.yml
- web/modules/custom/default_content_config/content/node/ea91eff1-f23a-4efc-a197-2606f95ced68.yml
[DIGITAL-526](https://cm-jira.usa.gov/browse/DIGITAL-526)
[DIGITAL-513](https://cm-jira.usa.gov/browse/DIGITAL-513)
Short Posts should always have a Source
Short Posts Type should not have a 'Service' Option
Edit a short post and check that 
- Source is a required field
- Type Dropdown does not list Service as an option
> DIGITAL-526 & DIGITAL-513: Shortpost Updates: Source Required & 'Service' type removal

- docs/releases.md
[DIGITAL-300](https://cm-jira.usa.gov/browse/DIGITAL-300)
Updated the documentation for releases to include the new scripting available.
> DIGITAL-300: Update release documentation.

- web/themes/custom/digital_gov/templates/node/node--landing-page--job-board.html.twig
[DIGITAL-608](https://cm-jira.usa.gov/browse/DIGITAL-608)
Make Job board "Apply" button more accessible for users of screen readers, voice control, and other assistive tools.
- Navigate to Jobboard
- Look at DOM/source to see `aria-label` attribute on the "Apply" button. It should say `Apply for [position name]`
Or
Use screen reader on the "Apply" button
> DIGITAL-608: Apply button accessibility updated

- scripts/migrate-all
- web/modules/custom/digital_gov_migration/digital_gov_migration.module
- web/modules/custom/digital_gov_migration/migrations/json_authors.yml
- web/modules/custom/digital_gov_migration/migrations/json_events.yml
- web/modules/custom/digital_gov_migration/migrations/json_guides.yml
- web/modules/custom/digital_gov_migration/migrations/json_news.yml
- web/modules/custom/digital_gov_migration/migrations/json_resources.yml
- web/modules/custom/digital_gov_migration/migrations/json_short_posts.yml
- web/modules/custom/digital_gov_migration/migrations/json_topics.yml
- web/modules/custom/digital_gov_migration/migrations/json_topics__featured_links_ext.yml
[DIGITAL-574](https://cm-jira.usa.gov/browse/DIGITAL-574)
Decodes HTML entities in needed fields during migrations.
`lando rebuild && lando si`
Then run migrate-all script.
No entities in fields for:
* author Kristen O'Nell
* news like /2022/10/14/sunrise-to-sunset-building-a-customer-centric-digital-ecosystem/, /2022/05/23/10-tips-to-create-maintain-and-present-non-english-digital-content-a-qa-with-michael-mule/, and /2020/03/17/updates-on-21st-century-idea-key/
* kicker on /event/2023/01/25/continuously-improve-your-website-by-using-customer-feedback-and-web-analytics-an-irs-case-study/
* host on /event/2022/07/20/white-house-and-gsa-open-innovation-forum-building-equitable-partnerships/
* summary on /event/2024/10/17/uswds-monthly-call-october-2024/
* short post title (should be on …
> DIGITAL-574: Decode HTML entities

- migrate-all.sh
- migrate-messages.sh
- web/modules/custom/digital_gov_migration/migrations/json_authors.yml
- web/modules/custom/digital_gov_migration/migrations/json_events.yml
- web/modules/custom/digital_gov_migration/migrations/json_guides.yml
- web/modules/custom/digital_gov_migration/migrations/json_news.yml
- web/modules/custom/digital_gov_migration/migrations/json_resources.yml
- web/modules/custom/digital_gov_migration/migrations/json_short_posts.yml
- web/modules/custom/digital_gov_migration/src/Plugin/migrate_plus/data_parser/JsonAuthors.php
[DIGITAL-605](https://cm-jira.usa.gov/browse/DIGITAL-605)
Updates the migration configurations to ignore topics which don't exists
Fixes two authors which were missing display names.
`lando rebuild && lando si`
Run migrate-all script.
Confirm theses pages came through
/resources/an-advanced-approach-to-accessibility/
/resources/an-introduction-to-accessibility/
/event/2023/11/16/uswds-monthly-call-november-2023/
/event/2022/10/20/october-2022-uswds-monthly-call/
/event/2022/08/18/uswds-monthly-call-august-2022/
/event/2022/07/20/white-house-and-gsa-open-innovation-forum-building-equitable-partnerships/
/event/2021/05/20/uswds-accessibility-creating-more-inclusive-federal-websites/
/2024/07/08/evaluating-your-agency-accessibility-just-got-a-whole-lot-easier-with-gsa-openacr-editor/ …
> DIGITAL-605 Missing content on import

- web/modules/custom/convert_text/src/ConvertText.php
- web/sites/default/settings.cloudgov.php
[DIGITAL-]()
Adds a wait between guzzle requests when following redirects.
Shows redirects being followed.
Updates hostname for stage environment.
No way to test this locally. YOu can confirm that the logos for short posts are showing up on the stage homepage now. That'll do it.
> DIGITAL-620 Stage errors

- web/themes/custom/digital_gov/digital_gov.theme
[DIGITAL-621](https://cm-jira.usa.gov/browse/DIGITAL-621)
Need to use target_id not revision_id to load the correct page nodes in the guide navigation.
`lando si` but its not strictly necessary
To recreate this bug on local, edit one more more guide nav objects and save it with "create a new revision" checked for the node **while you are on develop branch**. When you go to load any page in the guide, you should either see nav with the wrong links (if the revision ID happens to match the ID of an existing paragraph)  or a bunch of warnings:
When you switch to this branch, the navigation should be correct and stay the same even if you create a new revision of a guide nav node.
> DIGITAL-621: Fix guide nav links

- terraform/applications/nginx-waf/nginx/conf.d/default.conf
[DIGITAL-622](https://cm-jira.usa.gov/browse/DIGITAL-622)
Fix the production route in NGINX.
> DIGITAL-266: Fix NGINX prod route.

- web/modules/custom/default_content_config/content/node/fefddcf3-e162-4622-9176-a3f4c2dadd8e.yml
[DIGITAL-594](https://cm-jira.usa.gov/browse/DIGITAL-594)
Save untruncated deck for resources page.
`lando si` to reinstall the site and default content.
Visit the resources page, confirm the deck text is not cut off, should be:
```
Don't know where to start with a federal requirement? Aren't sure how to adopt a new technology with your team? Start here! We have resources for every level. Our collections are organized by popular topics, and they will help you meet the requirements of federal web legislation.
```
> DIGITAL-594: Resources default content

- config/sync/views.view.sidebar_communities.yml
[DIGITAL-568](https://cm-jira.usa.gov/browse/DIGITAL-568)
Update the filter for getting the footer count to only include highlighted communities.
`lando cim` to get the updated view.
ON an event page <https://digitalgov.lndo.site/event/2025/01/16/uswds-monthly-call-january-2025> confirm the sidebar community count is 8, not 9.
Same thing on an event page <https://digitalgov.lndo.site/2025/01/02/rebuilding-cdc-gov> and resources page <https://digitalgov.lndo.site/resources/delivering-digital-first-public-experience>
> DIGITAL-568: Fix community count

- config/sync/metatag.metatag_defaults.front.yml
- config/sync/metatag.metatag_defaults.global.yml
- web/themes/custom/digital_gov/templates/layout/html.html.twig
[DIGITAL-474](https://cm-jira.usa.gov/browse/DIGITAL-474)
updated various instances of metatag being incorrect or missing
`lando rebuild && lando si`
Test on homepage
- og:title - Site Name
- og:url - Base Site URL
- twitter:title - Site Name
test on any page
- twitter:site - @Digital_Gov ... note the case
- twitter:creator - @Digital_Gov ... note the case
- theme-color - #656bd7
> DIGITAL-474: Fix Metatags for search indexing

- web/modules/custom/default_content_config/content/node/e60a3199-17d7-4c13-8b76-f0bbaef67bcd.yml
[DIGITAL-541](https://cm-jira.usa.gov/browse/DIGITAL-541)
Past events links default content turned into a relative link
`lando si`
Visit Events page - https://digitalgov.lndo.site/events
Click Past events button. It should go to your local and not to the live site.
> DIGITAL-541: update past events link

- web/themes/custom/digital_gov/templates/partials/guides/guide-menu-bar.html.twig
Updates how we check if the desktop menubar should have a glossary link. Makes it same as he check used in mobile.
[DIGITAL-]()
`lando si`, though if you have an HCD guide set up already, you shouldn't need to rebuild local.
Go to <https://digitalgov.lndo.site/guides/introduction-human-centered-design> at desktop width, 
then scroll down enough so the guide menubar is sticky. 
and you should see the glossary icon next to the DG logo
> DIGITAL-632: Desktop menubar glossary link

- config/sync/core.entity_form_display.node.short_post.default.yml
- config/sync/field.field.node.short_post.field_external_url.yml
- config/sync/rabbit_hole.behavior_settings.node_type_short_post.yml
[DIGITAL-387](https://cm-jira.usa.gov/browse/DIGITAL-387)
If someone accesses the alias for a short post, they should be redirected to its external URL.
Make the alias field visible when editing a short post and updates the description of the external URL field to clarify the redirection.
`lando ci` should be sufficient.
Go to any short post and edit, confirm the alias field is visible.
In a private window, go to `https://digitalgov.lndo.site/THE_ALIAS`, confirm you're redirected to the external URL for that short post.
> DIGITAL-387: Short post redirects

- composer.lock
- composer.log
[DIGITAL-502](https://cm-jira.usa.gov/browse/DIGITAL-502)
Update Drupal core to 10.4.6 and Autocomplete deluxe module to 2.1.2
This should do it, if you don't want to go through a whole `lando si`
`./composer.sh install && ./drush.sh updatedb && ./drush.sh cache:rebuild`
Confirm drupal 10.4.6 is running in reports
> DIGITAL-502: Drupal updates

- config/sync/views.view.sidebar_communities.yml
- web/themes/custom/digital_gov/templates/views/views-view--sidebar-communities--attachment-1.html.twig
[DIGITAL-653](https://cm-jira.usa.gov/browse/DIGITAL-653)
Update the community sidebar view to count highlighted communities to show in the footer of the sidebar block.
`drush cim` to update the view should be sufficient.
Confirm highlighted community count is in sidebar
https://digitalgov.lndo.site/event/2024/10/17/uswds-monthly-call-october-2024
https://digitalgov.lndo.site/resources/an-advanced-approach-to-accessibility
https://digitalgov.lndo.site/2025/01/02/rebuilding-cdc-gov
Go to a news, event
> DIGITAL-653: Sidebar community count

- scripts/upkeep
[DIGITAL-]()
Fixes the property name for opengraph images.
> DIGITAL-651: OG tweak

- web/themes/custom/digital_gov/css/ckeditor.css
[DIGITAL-655](https://cm-jira.usa.gov/browse/DIGITAL-555)
Updates the z-index default for ckeditor modals so that the Linkit popup will display when editing embedded content.
`lando fe`
Create a new page or edit a page with embedded content like an accordion.
Add or edit the embedded content. Highlight some text for linking and press the Link button, it should be functional.
There is a weird side effect - once you invoke the link baloon, it will follow your cursor. I think that's OK for now, this restores functionality. There's quite a number of ckeditor in modal bugs being fixed in Drupal 11.
> DIGITAL-652: Linkit in modal

- terraform/applications/nginx-waf/nginx/snippets/proxy-to-app.conf.tmpl
- terraform/applications/nginx-waf/nginx/snippets/proxy-to-static.conf.tmpl
- terraform/applications/nginx-waf/nginx/snippets/proxy-to-storage.conf.tmpl
[DIGITAL-659](https://cm-jira.usa.gov/browse/DIGITAL-659)
Ensure that the HSTS header has the "preload" directive.
> DIGITAL-659: BOD 18-01 Compliance: Enable Full HSTS.

- composer.patches.json
- config/sync/core.extension.yml
- patches/tome-oom-deduplicate-paths.patch
- web/modules/custom/dg_tome/dg_tome.info.yml
- web/modules/custom/dg_tome/dg_tome.services.yml
- web/modules/custom/dg_tome/src/EventSubscriber/TomeEventSubscriber.php
[DIGITAL-658](https://cm-jira.usa.gov/browse/DIGITAL-658)
Don't export malformed paths that cause tome to overwrite an existing page with a redirect page.
Can't test this locally - I deployed a copy of this branch to stage.
Go to stage: https://digital-gov-static-staging.app.cloud.gov/communities
Confirm the multilingual, social-media, and user experience community pages load.
> DIGITAL-658 Fix tome redirects

- composer.patches.json
[DIGITAL-660](https://cm-jira.usa.gov/browse/DIGITAL-660)
Pulls in a patch for fixing Tome's pagination link rewrites.
`composer install` should be sufficient to get your local set up up-to-date. You will need enough content to have lots of pages of news/events to click through. `migrate-all.sh` is still there. 
See local setup, then run `robo.sh static`.
Go to the `/news` page, confirm that last page of news is `/news/page/38` not `news/page/48`
> DIGITAL-660: Fix tome pager links

- web/modules/custom/dg_tome/src/EventSubscriber/TomeEventSubscriber.php
[DIGITAL-663](https://cm-jira.usa.gov/browse/DIGITAL-663)
Adds a Tome event listener to export the sitewide alert data file so that banners render.
`drush cr` so that the new event listener is picked up.
Export the site (can do with with `lando si` and then `robo.sh static` which has a default configuration for the banners.
> DIGITAL-663: Adds a Tome event listener to export the sitewide alert data file so that sitewide banners render.

- MIGRATE.md
- config/sync/core.extension.yml
- migrate-all.sh
- migrate.sh
- web/modules/custom/dg_guide_nav/dg_guide_nav.info.yml
[DIGITAL-666](https://cm-jira.usa.gov/browse/DIGITAL-666)
* Disables the digital gov migration module.
* Adds call out to documentation about requirements for running migrations post-launch.
* Requires user confirmation to run migration helper scripts and prevent migrate helper scripts from running on prod and staging.
`lando si`
* Confirm Digital.gov migration module is disabled
* Can test that running migrate.sh or migrate-all.sh asks for confirmation to proceed.
* With the module disabled, running `migrate.sh json_topics`, for example, should error.
> DIGITAL-666: Post-launch disable migrations.
