config/sync/filter.format.html.yml

Instead of disabling the WYSIWYG, we can just disable the HTML filter and link converter.

Dont filter HTML or turn urls into links

---

CONTRIBUTING.md
README.md
RoboFile.php
composer.json
composer.lock
composer.log
composer.patches.json
config/sync/core.extension.yml
config/sync/menu_ui.settings.yml
patches/deafult_content_2698425.patch
web/modules/custom/default_content_config/default_content_config.info.yml

See the new CONTRIBUTING.md file.
Please create a node and use the documentation to learn how to export the content.
After you export the content, run `lando si` and your content should be created again.

Allow default content to be exported and updated contributing documentation

---

composer.json
composer.lock
composer.log
config/sync/core.extension.yml
web/modules/custom/convert_text/convert_text.info.yml
web/modules/custom/convert_text/convert_text.module
web/modules/custom/convert_text/convert_text.routing.yml
web/modules/custom/convert_text/src/ConvertText.php
web/modules/custom/convert_text/src/Form/ConvertTextForm.php

I used this text as my test text:
```
RAQ: |”&#8221;|
NBSP: | &nbsp;&nbsp;sdfsdf|
AMP: |&&amp;     |
QUOTE: |"&quot;|
SINGLEQ: |'&#039;|
LT:  |<&lt;|
GT: |>&gt;|
<span id="mooo">"some" &quot;stuff&quot;[A link](https://www.google.com)</span>
<span id='single-quotes'>Do single quotes get preserved&#039;?</span>
```
The new admin page can be found [here](http://digitalgov.lndo.site/admin/convert-text)
This is pretty confusing, but the idea is, that if it's destined for HTML and you take the converted text and paste it into the 'Source' of an HTML Drupal field, when you click off 'Source':
* The markdown should be html (I added a markdown link)
* All the crazy looking entities like &quot; and &#8221; should look like a " and ” instead.
* Non breaking spaces (&nbsp;) should cause ACTUAL space …

Convert text into plain or html for migration

---

config/sync/core.entity_form_display.node.short_post.default.yml
config/sync/core.entity_view_display.node.short_post.default.yml
config/sync/core.entity_view_display.node.short_post.teaser.yml
config/sync/field.field.node.short_post.field_external_url.yml
config/sync/field.storage.node.field_external_url.yml
config/sync/views.view.authmap.yml
config/sync/views.view.samlauth_map.yml
web/modules/custom/default_content_config/content/node/202c0f8c-2f2e-487a-8eed-e55fd949b41c.yml
web/modules/custom/default_content_config/content/node/30e4505c-8011-493a-a3e8-ad35ef95c29d.yml
web/modules/custom/default_content_config/content/node/30f086db-8fb5-40e8-ae3f-58dc8be40f74.yml
web/modules/custom/default_content_config/content/node/3c4bcc2c-26ae-4263-86c0-b770851f8e95.yml
web/modules/custom/default_content_config/content/node/853969b8-5390-4fe2-865a-c645aa81d1fd.yml
web/modules/custom/default_content_config/content/node/88a30df6-80b5-4887-bdb7-6ffb12259ac9.yml
web/modules/custom/default_content_config/content/node/8ba0f0bd-d728-4df0-bb05-28766df7a1c0.yml
web/modules/custom/default_content_config/content/node/d22455bc-ccf3-4079-a2bb-ecf67310af4b.yml
web/modules/custom/default_content_config/content/node/ea91eff1-f23a-4efc-a197-2606f95ced68.yml

[DIGITAL-107](https://cm-jira.usa.gov/browse/DIGITAL-107)
Adds the `external_url` field to the short post content type, this was missed during the initial setup.
Updated default content short posts with URL.
Given I click the short post content from the menu
When I visit the create short page page
Then I should see the external URL field in the form

DIGITAL-107: Add missing 'External URL' field to short post

---

.lando.dist.yml
README.md
docs/install-help.md

https://cm-jira.usa.gov/browse/DIGITAL-287

DIGITAL-287: Update README with suggested improvements

---

web/themes/custom/digital_gov/templates/media/media--document.html.twig

[DIGITAL-345](https://cm-jira.usa.gov/browse/DIGITAL-345)
**Default functionality for Media Type: Documents**
WHEN a media document is displayed (including if it is embedded via a WYSIWYG)
THEN the embed will display The **Media Name** and will href will be **Path to the File**
AND it will **not** display file size (if you see file size, then it should be manually entered as part of the media name)
`lando drush cr`
1. Visit [Media Testing Item](/media/16/edit) and take note of the "Name"
2. Compare the Name field to the name field embedded here [short code demo page](http://digitalgov.lndo.site/short-code-test-page)
-or-
1. Create a media document and enter a name that is different than the file name
2. Create a node and embed the media document into the node
3. View the node and you …

DIGITAL-345: Update display of Embedded Media Document to use media name

---

web/themes/custom/digital_gov/templates/block/block--site-wrapper-header.html.twig
web/themes/custom/digital_gov/templates/partials/search-gov-form.html.twig

[DIGITAL-440](https://cm-jira.usa.gov/browse/DIGITAL-440)
Added the following to the header of the site
- Search input form that will search search.gov
- "Subscribe to our newsletter" link above the search form
`lando si`
On header of any page of the site you should see:
- Search input form that will search search.gov via the URL https://find.digitalgov.gov/search
- "Subscribe to our newsletter" link above the search form 
- link will go to 404 Error because that content does not exist yet.
- If the "Subscribe to our newsletter" link color looks wrong that is because you are comparing a visited link to an unvisited link. 
Be sure to check that it shows in the responsive menu.

DIGITAL-440: Search.gov form in the header

---

composer.patches.json
patches/sitewide_alert_cache_tome.patch

[DIGITAL-478](https://cm-jira.usa.gov/browse/DIGITAL-478)
Fix Sitewide alert caching with TOME
1. Create a Site Alert in the Drupal UI https://digitalgov.lndo.site/admin/content/sitewide_alert
2. Generate the static site - `./robo.sh drupal-project:export-content && ./robo.sh static` 
3. Visit the site and you will see the Site Alert appears on the page correctly.
4. Stop the static site
5. Update the Site alert in the Drupal UI https://digitalgov.lndo.site/admin/content/sitewide_alert
6. Generate the static site - `./robo.sh drupal-project:export-content && ./robo.sh static` 
7. Visit the site and you will see the site alert has updated

DIGITAL-478: Add patch to make Sitewide alerts work with TOME

---

config/sync/views.view.glossary_sidebar.yml
web/themes/custom/digital_gov/templates/views/views-view-field--glossary-sidebar--accordion--name.html.twig

[DIGITAL-528](https://cm-jira.usa.gov/browse/DIGITAL-528)
The glossary accordion was opening the wrong item when clicked.
1. Nav to  https://digital-gov-static-dev.app.cloud.gov/guides/hcd
2. Click on "Glossary" and right side drawer pops out
3. Click on various accordion item
**Expected Result**: The accordion item that you click toggles open and closed when you click it

DIGITAL-528:Glossary Accordion Bug

---

config/sync/views.view.resource_topics_list.yml

[DIGITAL-540](https://cm-jira.usa.gov/browse/DIGITAL-540)
Updates the sort order to use the taxonomy weight instead of alphabetical sort.
Should be:
1. Design
2. Data & Analysis
3. Operations
4. Content & Communication
5. Technology
6. Strategic Development
<details>
<summary>Screenshot</summary>
</details>

DIGITAL-540: Updated resource topics list to use taxonomy weight for topics list and sort topics alphabetically

---

web/modules/custom/dg_breadcrumb/dg_breadcrumb.module

[DIGITAL-523](https://cm-jira.usa.gov/browse/DIGITAL-523)
Alters system breadcrumb block to cache per URL.
`lando si` should be sufficient for your environment. The tricky thing for testing this is to **enable** the config settings for cache bins.
1. Go to `/web/sites/default/settings.local.php`
2. Comment out:
- line 37 (leaving it enables dev twig debugging, disables render caching),
- line 65 (render cache again),
- line 87 (internal page cache),
-  line 96 (dynamic page page), 
Run `robo.sh static` to export the Drupal site to static files.
Verify that on the static pages:
- Event detail page has a breadcrumb where 2nd parent is "Events"
- Blog/News detail page has a breadcrumb where 2nd parent is "News"
- Resource detail page has a breadcrumb where 2nd parent is "Topics"
- Community …

DIGITAL-523: Fix tome-breadcrumbs

---

web/themes/custom/digital_gov/css/new/_buttons.scss

[DIGITAL-606](https://cm-jira.usa.gov/browse/DIGITAL-606)
On homepage, in the banner, when the user focuses on a button using they keyboard, there is not enough contrast in the visual indication of focus. it needs to be 3:1 ratio
`lando fe`
When you focus using your keyboard on the buttons in the homepage banner

DIGITAL-606: Update focus styles for banner buttons

---

config/sync/views.view.past_events.yml

[DIGITAL-569](https://cm-jira.usa.gov/browse/DIGITAL-569)
Add pagination to past events and show all, not just past 5
`lando rebuild && lando si`
There are not enough default content items to see the pagination when testing. You will need to adjust the number of items shown in the Past Event view (https://digitalgov.lndo.site/admin/structure/views/view/past_events) or add a bunch more events by running a migrate all locally.
The events page (https://digitalgov.lndo.site/events), Past events section should show pagination when you are over 20 past events.

DIGITAL-569: Show all past events using pagination

---

config/sync/metatag.metatag_defaults.front.yml

[DIGITAL-474](https://cm-jira.usa.gov/browse/DIGITAL-474)
Inaccurate meta tag value on the homepage Canonical URL
`lando si`
- View source or DOM on **homepage**
- Search for "canonical"
- It should should be the site root as an absolute path.

DIGITAL-474: Correct the home default canonical meta tag

---

web/themes/custom/digital_gov/css/new/shortcodes/_note.scss

[DIGITAL-593](https://cm-jira.usa.gov/browse/DIGITAL-593)
- CKEditor automatically wraps text not within a container with a `<p>` element. 
- `.dg-note` did not always use a `<p>` within them in the past.
- `<p>` tags have a max-width for readability.
**Result**: Text that did not have a max-width before now inherit one from their container. This is causing the them to line-break earlier. We followed the guidelines on USWDS and increased the width of paragraphs within a `.dg-note` 
`lando fe`
- Navigate to https://digitalgov.lndo.site/communities/community-guidelines
- Edit the DOM and remove the Dos and Don't table from lower down on the page (Another bug should not interfere with testing this one - [DIGITAL-626](https://cm-jira.usa.gov/browse/DIGITAL-626))
- Visually compare to Live …

DIGITAL-593: Increase paragraph width within a dg-note

---

web/modules/custom/ec_shortcodes/src/Plugin/EmbeddedContent/ECShortcodesAccordion.php
web/modules/custom/ec_shortcodes/templates/ec-shortcodes-accordion.html.twig
web/modules/custom/ec_shortcodes/templates/ec-shortcodes-card-policy.html.twig

[DIGITAL-642](https://cm-jira.usa.gov/browse/DIGITAL-642)
Accordions and Policy cards (restyled accordions) are not opening correctly if there are more than one on the page.
`lando drush cr` should do it
**Test 1**
Add more than one accordion to the same page
When the accordion is clicked, it should only effect itself
**Test 2**
Test if you can edit the accordion. (this was broken when testing the other, fixed this too)
**Test 3**
Add more than one Policy Card to the same page
When the Policy Card is clicked, it should only effect itself
url of live content - https://digitalgov.lndo.site/resources/required-web-content-and-links

DIGITAL-642: Fix broken accordions when there are multiples

---

config/sync/views.view.news_and_events.yml
config/sync/views.view.topic_news_and_events.yml

[DIGITAL-641](https://cm-jira.usa.gov/browse/DIGITAL-641)
Archived nodes are displaying on /blogs and Topic pages.
`lando si`
1. View /blog page
2. Edit one of the events and mark it as archived
3. Revisit /blog page
**Expected Result**: The archived blog should not display
Do the same for:
- /blog - News Node
- Topic page - Event Node
- Topic Page - News Node

DIGITAL-641: Filtered news+events views to just show published

---

web/themes/custom/digital_gov/templates/node/node--event--teaser.html.twig
web/themes/custom/digital_gov/templates/node/node--news--teaser.html.twig

[DIGITAL-643](https://cm-jira.usa.gov/browse/DIGITAL-643)
1. News teaser card images, do not check if there is an image before rendering the image - results in an empty image `src`
2. Event teaser cards, renders the incorrect datetime format
`lando cr`
1. News teaser card images
- Create a news item without a image associated, view homepage, check that the card does not render an img with an empty `src`.
3. Event teaser cards
- View homepage, view dom, search for `card-event__datetime` - **Result**: `datetime` attr should be in the format Y-m-d

DIGITAL-643: Minor Markup Issues

---

config/sync/user.role.author.yml
config/sync/user.role.content_admin.yml
config/sync/user.role.editor.yml
config/sync/user.role.publisher.yml

[DIGITAL-542](https://cm-jira.usa.gov/browse/DIGITAL-542)
Give user ability to set the URL path on their content creations within the workflow
`lando si`
Login as each of the following: Author, Editor, Publisher, Content Admin
Edit content and looks to see if user can update the path
Remember some content roles can only edit content in a certain state, this is most important with the Editor role. It can only interact with content in the "Ready for Review" State.

DIGITAL-542: Add URL Alias permission to content workflow users

---

web/modules/custom/dg_guide_nav/dg_guide_nav.module
web/themes/custom/digital_gov/templates/partials/guides/guide-menu-bar.html.twig

Fixes setting which menubar item to highlight as current when viewing a page in the subnav.
[DIGITAL-571](https://cm-jira.usa.gov/browse/DIGITAL-571)
Fixes setting which menubar item to highlight as current when viewing a page in the subnav.
`lando si`
1. Visit https://digitalgov.lndo.site/guides/desk-research#content-start (a subpage of page in the guide nav)
2. At desktop width, You should see "Framing" marked as current with the blue underline in the guide menubar.
3. On mobile width, you should see "framing" marked as current with blue text in the mobile hamburger guide navigation.
4. Navigationg the top-level guide pages should be unchanged (i.e., the page is highlighted and its subnav is shown on left)
Like this but I have migrated content, not the default content:

DIGITAL-571: Subnav current

---

scripts/upkeep

[DIGITAL-651](https://cm-jira.usa.gov/browse/DIGITAL-651)
Fix upkeep script for images URL not appearing on search.gov.

DIGITAL-651: Fix for images not appearing on search.gov

---

web/modules/custom/dg_guide_nav/dg_guide_nav.module

[DIGITAL-571](https://cm-jira.usa.gov/browse/DIGITAL-571)
Need to reset the subnav links for each item to prevent …a previous subnav's links from showing up in an adjacent subnav when the sibling doesn't have a subnav.
Not sure how to set this up on local, the default content isn't configured with this scenario. Migrated content requires manual set up of the guide navs as they are on prod.
Currently on prod, the bug is on some guide navs. If a page doesn't have a subnav, the previous subnav is re-used.
Case <https://digital-gov-drupal-prod.app.cloud.gov/guides/hcd/discovery-concepts/find-opportunities#content-start> The "Discover" page doesn't have any sub nav pages, but the "Goals and Insights" link is showing because it's a link in the previous page.
With this fix, that same set up on …

DIGITAL-571: Guidenav reset subs

---

web/themes/custom/digital_gov/templates/node/node--community.html.twig

[DIGITAL-593](https://cm-jira.usa.gov/browse/DIGITAL-593)
Community node pages have an extra div wrapping the content. This breaks the `.usa-prose` styles because that class expects a direct child to accept the styles.
`lando fe`
View a comunity page
1. Search the DOM for `.content`
2. There should only be one class that matches that

DIGITAL-593: Remove extra wrapper breaking prose styles

---

web/modules/custom/ec_shortcodes/src/Plugin/EmbeddedContent/ECShortcodesFeaturedResource.php

[DIGITAL-657](https://cm-jira.usa.gov/browse/DIGITAL-657)
Guides could not be added as Featured Resource because the machine name was misspelled in the autocomplete. Where it had been added by a migration, it could not be updated because it broke the reference.
`lando drush cr`
Add a Featured resource embedded content that is a guide to a WYSIWYG.
save the node and try to edit it.
If you have migrated content locally then you can try and update the following node's Featured Resources.
/guides/hcd/introduction/approach

DIGITAL-657: Fix featured resources autocomplete bundle definition 

---

terraform/applications/nginx-waf/nginx/snippets/ip-restrict-cms.conf.tmpl
terraform/infra/locals.tf

[DIGITAL-323](https://cm-jira.usa.gov/browse/DIGITAL-323)
Restricts CMS access to the GSA address pool.

DIGITAL-323: Secure CMS behind corporate proxy.

---

terraform/infra/backend.tf
terraform/infra/locals.tf
terraform/infra/provider.tf

This PR updates the IP restrictions in locals.tf to allow VPN access:
- Added required VPN IP networks (149.142.0.0/16, 149.143.0.0/16, 149.144.0.0/16, 159.142.0.0/16, 192.168.50.0/24)
- Restructured locals.tf to remove circular dependencies
- Added complete WAF application configuration

DIGITAL-323: Update VPN IP restrictions in locals.tf
